name: ff_bloc
description: FF bloc for creating awesome apps easy
version: 1.0.0
repository: https://github.com/Gorniv/ff_bloc
publish_to: https://pub.dev/


environment:
  sdk: '>=2.18.4'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 
  equatable: ^2.0.0
  get_it: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0